url: https://sahilbathlaofficial.github.io
# baseurl: /proapps/
# baseurl:

# Site settings
title: Decabits
email: sahilbathla1@gmail.com
description: "Zyloto provides a end to end software solution. From design to web/mobile development to quality ensurance, we cover it all. Technologies :- Ruby on Rails, Angular, Node, React, Android & IOS"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Sahil Batla
  pic: 1
  position: Team Head & Lead Developer
  social:
    - title: twitter
      url: https://twitter.com/sahilbathla
    - title: facebook
      url: https://www.facebook.com/sahilbathla1
    - title: stack-overflow
      url: http://stackoverflow.com/users/3122241/sahilbathla

- name: Harnoor Kaur Gulati
  pic: 2
  position: HR Manager
  social:
    - title: twitter
      url: 
    - title: facebook
      url: https://www.facebook.com/harnoor.gulati
    - title: stack-overflow
      url: 

- name: Shubham Jain
  pic: 3
  position: Software Developer
  social:
    - title: twitter
      url: https://twitter.com/shubjain440
    - title: facebook
      url: https://www.facebook.com/shubjain1995
    - title: stack-overflow
      url: https://stackoverflow.com/users/6674602/shubham-jain


- name: Sonal Gupta
  pic: 4
  position: QA Engineer
  social:
    - title: twitter
      url: https://twitter.com/sonalrulez16
    - title: facebook
      url: https://www.facebook.com/sonalrulez
    - title: stack-overflow
      url: https://stackoverflow.com/users/11451615/sonal-gupta

- name: Tanveer Singh
  pic: 5
  position: Software Developer
  social:
    - title: twitter
      url: 
    - title: facebook
      url: https://www.facebook.com/catalystos  
    - title: stack-overflow
      url: https://stackexchange.com/users/15872566/tanveer-singh

- name: Shubham Gupta
  pic: 6
  position: Software Developer
  social:
    - title: twitter
      url: 
    - title: facebook
      url: 
    - title: stack-overflow
      url: https://stackoverflow.com/users/9671931/shubham-gupta

- name: Ayush Gupta
  pic: 7
  position: Software Developer
  social:
    - title: twitter
      url: 
    - title: facebook
      url: https://www.facebook.com/ayushgupta123456
    - title: stack-overflow
      url: 

- name: Vishal Raghav
  pic: 8
  position: Software Developer
  social:
    - title: twitter
      url: 
    - title: facebook
      url: https://www.facebook.com/vishal.raghav.7
    - title: stack-overflow
      url: 

- name: Rashmi Singh
  pic: 9
  position: Software Developer
  social:
    - title: twitter
      url: 
    - title: facebook
      url: https://www.facebook.com/RashmiSingh995
    - title: stack-overflow
      url: https://stackoverflow.com/users/6657635/rashmi-singh

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty